// @ts-check
import path from 'path';
import Router from './route-handler.js';

/** @typedef {import('./route-handler.js').default} RouterClass */
/** @typedef {import('./route-handler.js').RouteOptions} RouteOptions */

/** @type {Promise<{ name: string, version: string, description: string }> | null} */
let packageMetadataPromise = null;
/** @type {Promise<{ css: string, script: string }> | null} */
let docsAssetsPromise = null;

/** @param {string | undefined} value @param {string} fallback */
function normalizePublicPath(value, fallback) {
    const source = value && value.trim().length > 0 ? value.trim() : fallback;
    const withLeadingSlash = source.startsWith('/') ? source : `/${source}`;
    if (withLeadingSlash === '/')
        return fallback;
    return withLeadingSlash.replace(/\/+$/, '');
}

const OPENAPI_JSON_PATH = normalizePublicPath(process.env.OPENAPI_JSON_PATH, '/openapi.json');
const OPENAPI_DOCS_PATH = normalizePublicPath(process.env.OPENAPI_DOCS_PATH, '/api-docs');

/** @returns {Promise<{ name: string, version: string, description: string }>} */
async function getPackageMetadata() {
    if (!packageMetadataPromise) {
        packageMetadataPromise = (async () => {
            const packageFile = Bun.file(path.join(process.cwd(), 'package.json'));
            if (await packageFile.exists()) {
                const json = await packageFile.json();
                return {
                    name: typeof json.name === 'string' && json.name.length > 0 ? json.name : 'Tachyon API',
                    version: typeof json.version === 'string' && json.version.length > 0 ? json.version : '2.0.0',
                    description: typeof json.description === 'string' && json.description.length > 0
                        ? json.description
                        : 'HTTP API generated by Tachyon',
                };
            }
            return {
                name: 'Tachyon API',
                version: '2.0.0',
                description: 'HTTP API generated by Tachyon',
            };
        })();
    }
    return packageMetadataPromise;
}

/** @returns {Promise<{ css: string, script: string }>} */
async function getDocsAssets() {
    if (!docsAssetsPromise) {
        docsAssetsPromise = (async () => {
            const docsDir = path.join(import.meta.dir, "../runtime/docs");
            const [css, script] = await Promise.all([
                Bun.file(path.join(docsDir, "openapi-docs.css")).text(),
                Bun.file(path.join(docsDir, "openapi-docs.js")).text(),
            ]);
            return { css, script };
        })();
    }
    return docsAssetsPromise;
}

/** @param {number | string} status */
function describeStatus(status) {
    const numeric = Number(status);
    if (numeric === 200)
        return 'Successful response';
    if (numeric === 201)
        return 'Resource created';
    if (numeric === 204)
        return 'No content';
    if (numeric === 400)
        return 'Bad request';
    if (numeric === 401)
        return 'Unauthorized';
    if (numeric === 403)
        return 'Forbidden';
    if (numeric === 404)
        return 'Not found';
    if (numeric === 422)
        return 'Validation error';
    if (numeric === 429)
        return 'Too many requests';
    if (numeric >= 500 && numeric < 600)
        return 'Server error';
    return `HTTP ${status}`;
}

/** @param {string} route */
function routeToOpenApiPath(route) {
    return route.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
}

/** @param {string} route */
function routeTags(route) {
    const segments = route.split('/').filter(Boolean);
    if (segments.length === 0)
        return ['root'];
    return [segments[0]];
}

/**
 * @param {string} route
 * @param {string} method
 */
function operationId(route, method) {
    const normalizedRoute = route === '/'
        ? 'root'
        : route
            .replace(/^\//, '')
            .replace(/[:{}]/g, '')
            .replace(/[^A-Za-z0-9/]+/g, '')
            .split('/')
            .filter(Boolean)
            .join('_');
    return `${method.toLowerCase()}_${normalizedRoute}`;
}

/** @param {unknown} schema @returns {Record<string, unknown>} */
function schemaFromValue(schema) {
    if (schema === null)
        return { type: 'null' };
    if (Array.isArray(schema)) {
        if (schema.length === 0)
            return { type: 'array', items: {} };
        if (schema.length === 1) {
            return { type: 'array', items: schemaFromValue(schema[0]) };
        }
        return {
            type: 'array',
            items: {
                oneOf: schema.map((item) => schemaFromValue(item)),
            },
        };
    }
    switch (typeof schema) {
        case 'string':
            return { type: 'string' };
        case 'number':
            return Number.isInteger(schema)
                ? { type: 'integer', example: schema }
                : { type: 'number', example: schema };
        case 'boolean':
            return { type: 'boolean', example: schema };
        case 'object':
            return objectSchema(/** @type {Record<string, unknown>} */ (schema));
        default:
            return {};
    }
}

/** @param {Record<string, unknown>} schema @returns {Record<string, unknown>} */
function objectSchema(schema) {
    const entries = Object.entries(schema);
    if (entries.length === 1 && entries[0][0] === '') {
        return {
            type: 'object',
            additionalProperties: schemaFromValue(entries[0][1]),
        };
    }

    /** @type {Record<string, unknown>} */
    const properties = {};
    /** @type {string[]} */
    const required = [];
    /** @type {Record<string, unknown>} */
    const patternProperties = {};

    for (const [rawKey, value] of entries) {
        const isOptional = rawKey.endsWith('?');
        const normalizedKey = isOptional ? rawKey.slice(0, -1) : rawKey;
        const isPattern = normalizedKey.startsWith('^') && normalizedKey.endsWith('$') && typeof value === 'string';
        const propertyName = isPattern
            ? normalizedKey.slice(1, -1)
            : normalizedKey;
        const propertySchema = schemaFromValue(value);
        if (isPattern && typeof value === 'string') {
            patternProperties[`^${propertyName}$`] = {
                type: 'string',
                pattern: value,
            };
            continue;
        }
        properties[propertyName] = propertySchema;
        if (!isOptional)
            required.push(propertyName);
    }

    /** @type {Record<string, unknown>} */
    const result = {
        type: 'object',
        properties,
    };
    if (required.length > 0)
        result.required = required;
    if (Object.keys(patternProperties).length > 0)
        result.patternProperties = patternProperties;
    return result;
}

/**
 * @param {string} route
 * @param {string} method
 * @param {Record<string, unknown>} methodSchema
 */
function buildOperation(route, method, methodSchema) {
    /** @type {Array<Record<string, unknown>>} */
    const parameters = [];
    const routeParamNames = [...route.matchAll(/:([A-Za-z0-9_]+)/g)].map((match) => match[1]);
    for (const paramName of routeParamNames) {
        parameters.push({
            name: paramName,
            in: 'path',
            required: true,
            schema: { type: 'string' },
        });
    }

    const requestSchema = /** @type {Record<string, unknown> | undefined} */ (methodSchema.req ?? methodSchema.request);
    /** @type {Record<string, unknown> | undefined} */
    let requestBody;
    if (requestSchema && typeof requestSchema === 'object' && !Array.isArray(requestSchema)) {
        const pathParams = /** @type {Record<string, unknown> | undefined} */ (requestSchema.paths);
        if (pathParams && typeof pathParams === 'object' && !Array.isArray(pathParams)) {
            for (const [name, value] of Object.entries(pathParams)) {
                if (routeParamNames.includes(name))
                    continue;
                parameters.push({
                    name,
                    in: 'path',
                    required: true,
                    schema: schemaFromValue(value),
                });
            }
        }
        const queryParams = /** @type {Record<string, unknown> | undefined} */ (requestSchema.query);
        if (queryParams && typeof queryParams === 'object' && !Array.isArray(queryParams)) {
            for (const [name, value] of Object.entries(queryParams)) {
                const required = !name.endsWith('?');
                parameters.push({
                    name: required ? name : name.slice(0, -1),
                    in: 'query',
                    required,
                    schema: schemaFromValue(value),
                });
            }
        }
        const headerParams = /** @type {Record<string, unknown> | undefined} */ (requestSchema.headers);
        if (headerParams && typeof headerParams === 'object' && !Array.isArray(headerParams)) {
            for (const [name, value] of Object.entries(headerParams)) {
                const required = !name.endsWith('?');
                parameters.push({
                    name: required ? name : name.slice(0, -1),
                    in: 'header',
                    required,
                    schema: schemaFromValue(value),
                });
            }
        }
        if (Object.hasOwn(requestSchema, 'body')) {
            requestBody = {
                required: method !== 'GET' && method !== 'HEAD',
                content: {
                    'application/json': {
                        schema: schemaFromValue(requestSchema.body),
                    },
                },
            };
        }
    }

    /** @type {Record<string, unknown>} */
    const responses = {};
    for (const [status, schema] of Object.entries(methodSchema)) {
        if (!/^\d{3}$/.test(status))
            continue;
        /** @type {Record<string, unknown>} */
        const response = {
            description: describeStatus(status),
        };
        if (status !== '204' && schema && typeof schema === 'object' && Object.keys(schema).length > 0) {
            response.content = {
                'application/json': {
                    schema: schemaFromValue(/** @type {Record<string, unknown>} */ (schema)),
                },
            };
        }
        responses[status] = response;
    }
    if (Object.keys(responses).length === 0) {
        responses.default = {
            description: 'Default response',
        };
    }

    /** @type {Record<string, unknown>} */
    const operation = {
        operationId: operationId(route, method),
        tags: routeTags(route),
        responses,
    };
    if (parameters.length > 0)
        operation.parameters = parameters;
    if (requestBody)
        operation.requestBody = requestBody;
    if (process.env.BASIC_AUTH || process.env.BASIC_AUTH_HASH)
        operation.security = [{ basicAuth: [] }];
    return operation;
}

/** @param {Request} request */
async function buildSpec(request) {
    const metadata = await getPackageMetadata();
    /** @type {Record<string, Record<string, unknown>>} */
    const paths = {};
    for (const [route, schema] of Object.entries(Router.routeConfigs)) {
        if (!schema || typeof schema !== 'object')
            continue;
        const openApiPath = routeToOpenApiPath(route);
        if (!paths[openApiPath])
            paths[openApiPath] = {};
        for (const [method, methodSchema] of Object.entries(schema)) {
            if (!methodSchema || typeof methodSchema !== 'object')
                continue;
            paths[openApiPath][method.toLowerCase()] = buildOperation(route, method, /** @type {Record<string, unknown>} */ (methodSchema));
        }
    }
    if (!paths['/health']) {
        paths['/health'] = {
            get: {
                operationId: 'get_health',
                tags: ['system'],
                responses: {
                    '200': {
                        description: 'Health check',
                        content: {
                            'application/json': {
                                schema: {
                                    type: 'object',
                                    properties: {
                                        status: { type: 'string', example: 'ok' },
                                        uptimeMs: { type: 'number' },
                                    },
                                    required: ['status', 'uptimeMs'],
                                },
                            },
                        },
                    },
                },
            },
        };
    }
    if (!paths['/ready']) {
        paths['/ready'] = {
            get: {
                operationId: 'get_ready',
                tags: ['system'],
                responses: {
                    '200': {
                        description: 'Readiness check',
                        content: {
                            'application/json': {
                                schema: {
                                    type: 'object',
                                    properties: {
                                        status: { type: 'string', example: 'ready' },
                                        uptimeMs: { type: 'number' },
                                    },
                                    required: ['status', 'uptimeMs'],
                                },
                            },
                        },
                    },
                },
            },
        };
    }

    /** @type {Record<string, unknown>} */
    const spec = {
        openapi: '3.1.0',
        info: {
            title: process.env.OPENAPI_TITLE || metadata.name,
            version: metadata.version,
            description: process.env.OPENAPI_DESCRIPTION || metadata.description,
        },
        servers: [{ url: new URL(request.url).origin }],
        paths,
    };
    if (process.env.BASIC_AUTH || process.env.BASIC_AUTH_HASH) {
        spec.components = {
            securitySchemes: {
                basicAuth: {
                    type: 'http',
                    scheme: 'basic',
                },
            },
        };
    }
    return spec;
}

function docsContentSecurityPolicy() {
    return "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'";
}

function docsHtml() {
    return `<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tachyon API Docs</title>
    <link rel="stylesheet" href="${OPENAPI_DOCS_PATH}/app.css">
</head>
<body>
    <main id="docs-app" class="docs-shell">
        <section class="hero">
            <div class="hero-copy">
                <p class="eyebrow">Tachyon API Docs</p>
                <h1>OpenAPI rendered with a Tachyon-native interactive console.</h1>
                <p class="lede">Inspect operations, authorize requests, edit parameters, execute calls, and compare live responses without shipping a third-party Swagger bundle.</p>
                <div class="hero-actions">
                    <a href="${OPENAPI_JSON_PATH}" class="button button-primary">Open JSON spec</a>
                    <a href="/" class="button button-secondary">Back to app</a>
                </div>
            </div>
        </section>
        <section class="toolbar">
            <div class="toolbar-panel">
                <div class="toolbar-grid">
                    <label class="field">
                        <span>Search operations</span>
                        <input id="docs-filter" type="search" placeholder="Filter by path, method, tag, or operation id">
                    </label>
                    <label class="field">
                        <span>Server</span>
                        <select id="docs-server" aria-label="Server"></select>
                    </label>
                    <div class="toolbar-actions">
                        <button type="button" class="button button-secondary" data-action="expand-all">Expand all</button>
                        <button type="button" class="button button-secondary" data-action="collapse-all">Collapse all</button>
                    </div>
                </div>
            </div>
            <details class="toolbar-panel" open>
                <summary class="section-header">
                    <h2>Authorize</h2>
                    <span class="badge">Persistent for this browser session</span>
                </summary>
                <p class="muted">Any security schemes declared in the OpenAPI document show up here. The docs console applies them automatically when you execute an operation.</p>
                <div id="docs-auth" class="auth-grid">
                    <p class="muted">Loading security schemes…</p>
                </div>
                <div class="toolbar-actions">
                    <button type="button" class="button button-secondary" data-action="clear-auth">Clear authorization</button>
                </div>
            </details>
        </section>
        <section class="summary-grid" id="docs-summary">
            <article class="summary-card">
                <span class="summary-label">Status</span>
                <strong>Loading schema</strong>
            </article>
        </section>
        <section class="content-grid">
            <aside class="sidebar">
                <div class="panel">
                    <h2>Routes</h2>
                    <nav id="docs-nav" class="route-nav"></nav>
                </div>
            </aside>
            <section class="main-panel">
                <div class="panel">
                    <div class="panel-header">
                        <h2>Operations</h2>
                        <span id="docs-origin" class="badge">origin pending</span>
                    </div>
                    <div id="docs-routes" class="route-list">
                        <article class="route-card">
                            <p class="muted">Fetching the live OpenAPI document…</p>
                        </article>
                    </div>
                </div>
            </section>
        </section>
    </main>
    <script type="module" src="${OPENAPI_DOCS_PATH}/app.js"></script>
</body>
</html>`;
}

/**
 * @param {string} route
 * @param {Response} response
 * @returns {Response}
 */
function withDocsHeaders(route, response) {
    const headers = new Headers(response.headers);
    headers.set('Cache-Control', route === '/openapi.json' ? 'no-cache, must-revalidate' : 'no-cache, must-revalidate');
    headers.set('Content-Security-Policy', docsContentSecurityPolicy());
    return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers,
    });
}

async function docsStyles() {
    return (await getDocsAssets()).css;
}

async function docsScript() {
    const { script } = await getDocsAssets();
    return script
        .replace('__OPENAPI_PATH__', OPENAPI_JSON_PATH)
        .replace('__OPENAPI_DOCS_PATH__', OPENAPI_DOCS_PATH);
}

export default class OpenAPI {
    static registerRoutes() {
        Router.reqRoutes[OPENAPI_JSON_PATH] = {
            GET: async (request = new Request(`http://localhost${OPENAPI_JSON_PATH}`)) => {
                const response = Response.json(await buildSpec(request), {
                    status: 200,
                    headers: Router.getHeaders(request),
                });
                return withDocsHeaders(OPENAPI_JSON_PATH, response);
            },
        };
        const docsHandler = async (request = new Request(`http://localhost${OPENAPI_DOCS_PATH}`)) => {
            const response = new Response(docsHtml(), {
                status: 200,
                headers: {
                    ...Router.getHeaders(request),
                    'Content-Type': 'text/html; charset=utf-8',
                },
            });
            return withDocsHeaders(OPENAPI_DOCS_PATH, response);
        };
        Router.reqRoutes[OPENAPI_DOCS_PATH] = { GET: docsHandler };
        Router.reqRoutes[`${OPENAPI_DOCS_PATH}/`] = { GET: docsHandler };
        Router.reqRoutes[`${OPENAPI_DOCS_PATH}/app.css`] = {
            GET: async (request = new Request(`http://localhost${OPENAPI_DOCS_PATH}/app.css`)) => {
                const response = new Response(await docsStyles(), {
                    status: 200,
                    headers: {
                        ...Router.getHeaders(request),
                        'Content-Type': 'text/css; charset=utf-8',
                    },
                });
                return withDocsHeaders(`${OPENAPI_DOCS_PATH}/app.css`, response);
            },
        };
        Router.reqRoutes[`${OPENAPI_DOCS_PATH}/app.js`] = {
            GET: async (request = new Request(`http://localhost${OPENAPI_DOCS_PATH}/app.js`)) => {
                const response = new Response(await docsScript(), {
                    status: 200,
                    headers: {
                        ...Router.getHeaders(request),
                        'Content-Type': 'application/javascript; charset=utf-8',
                    },
                });
                return withDocsHeaders(`${OPENAPI_DOCS_PATH}/app.js`, response);
            },
        };
    }
}
