// Tachyon application globals generated by `ty init`.
// This contract is standalone and intentionally contains no legacy runtime imports.

declare module '/shared/modules/*' {
  const value: unknown;
  export default value;
}

declare module '*.css' {
  const value: string;
  export default value;
}

declare global {
  interface HTMLElement {
    tachyonComponent?: {
      instance?: object;
      refresh?: () => void | Promise<void>;
      controller?: AbortController;
    };
  }

  type TacProps = Record<string, unknown>;
  interface TacPlatformContext {
    platform: 'web' | 'native';
    environment: 'browser' | 'server' | 'native';
    os: 'android' | 'ios' | 'linux' | 'macos' | 'web' | 'windows' | 'unknown';
    target: string;
  }

  const Tac: abstract new (...args: any[]) => object;
  const env: (name: string) => PropertyDecorator;
  const onMount: MethodDecorator;
  const publish: (topic: string, value: unknown) => Promise<unknown>;
  const subscribe: (topic: string, listener: (value: unknown) => void | Promise<void>) => () => void;
  const platform: TacPlatformContext['platform'];
  const environment: TacPlatformContext['environment'];
  const os: TacPlatformContext['os'];
  const target: TacPlatformContext['target'];

  const app: {
    isAvailable(): boolean;
    info(): Promise<Record<string, unknown>>;
  };
  const clipboard: {
    readText(): Promise<string>;
    writeText(text: string): Promise<unknown>;
  };
  const fileSystem: {
    readText(path: string): Promise<{ path: string; text: string }>;
    writeText(path: string, text: string): Promise<{ path: string; bytes: number; written: boolean }>;
    readDir(path: string): Promise<{ path: string; entries: Array<{ name: string; type: 'file' | 'directory' }> }>;
    stat(path: string): Promise<{ path: string; exists: boolean; type?: 'file' | 'directory'; size?: number }>;
    mkdir(path: string): Promise<{ path: string; created: boolean }>;
    remove(path: string): Promise<{ path: string; removed: boolean }>;
    paths(): Promise<{ appData: string; cache: string; documents?: string }>;
  };
  const shell: {
    exec(command: string, args?: string[], cwd?: string): Promise<{ command: string; args: string[]; exitCode: number; stdout: string; stderr: string }>;
  };
  const browser: {
    open(url: string): Promise<{ opened: boolean }>;
  };
  const share: {
    text(text: string, title?: string): Promise<{ shared: boolean }>;
  };
  const haptics: {
    impact(): Promise<{ impacted: boolean }>;
  };
  const filePicker: {
    openText(): Promise<{ name: string; text: string }>;
    saveText(name: string, text: string): Promise<{ name: string; saved: boolean }>;
  };
  const secrets: {
    get(key: string): Promise<string | null>;
    set(key: string, value: string): Promise<void>;
    delete(key: string): Promise<void>;
  };
  const auth: {
    verifyUser(reason: string): Promise<{ verified: boolean; method: 'biometric' | 'device-credential' }>;
  };
  const geolocation: {
    current(options?: PositionOptions): Promise<{
      latitude: number;
      longitude: number;
      accuracy: number;
      altitude: number | null;
      altitudeAccuracy: number | null;
      heading: number | null;
      speed: number | null;
      timestamp: number;
    }>;
  };
  const notifications: {
    show(title: string, options?: NotificationOptions): Promise<{ shown: boolean }>;
  };
  const media: {
    getUserMedia(constraints: MediaStreamConstraints): Promise<MediaStream>;
  };

  interface TachyonShortcut {
    id: string;
    accelerator: string;
  }
  interface TachyonShortcutListResult {
    shortcuts: TachyonShortcut[];
  }
  const host: {
    invoke<T = unknown>(operation: string, payload?: unknown): Promise<T>;
    on<T = unknown>(event: string, handler: (payload: T) => void): () => void;
  };
  const shortcuts: {
    register(options: { id: string; accelerator: string; replace?: boolean }): Promise<TachyonShortcutListResult & { shortcut: TachyonShortcut }>;
    unregister(id: string): Promise<TachyonShortcutListResult & { unregistered: boolean }>;
    unregisterAll(): Promise<TachyonShortcutListResult & { unregistered: number }>;
    list(): Promise<TachyonShortcutListResult>;
  };

  interface TachyonAppWindowState {
    mode?: 'normal' | 'minimized' | 'maximized' | 'fullscreen';
    alwaysOnTop: boolean;
    opacity: number;
    clickThrough?: boolean;
    captureProtection?: boolean;
  }
  const appWindow: {
    state(): Promise<TachyonAppWindowState>;
    setAlwaysOnTop(enabled: boolean): Promise<TachyonAppWindowState | { updated: true }>;
    setOpacity(value: number): Promise<TachyonAppWindowState | { updated: true }>;
    setClickThrough(enabled: boolean): Promise<TachyonAppWindowState>;
    setCaptureProtection(enabled: boolean): Promise<TachyonAppWindowState>;
  };

  interface TachyonContentSurfaceState {
    id: string;
    open: boolean;
    presentation?: 'composed' | 'detached';
    persistentSession?: boolean;
    url?: string;
    loading?: boolean;
    canGoBack?: boolean;
    canGoForward?: boolean;
  }
  const contentSurface: {
    open(options: { id: string; url: string; persistentSession?: boolean }): Promise<TachyonContentSurfaceState>;
    navigate(id: string, url: string): Promise<TachyonContentSurfaceState>;
    state(id: string): Promise<TachyonContentSurfaceState>;
    goBack(id: string): Promise<TachyonContentSurfaceState>;
    goForward(id: string): Promise<TachyonContentSurfaceState>;
    reload(id: string): Promise<TachyonContentSurfaceState>;
    close(id: string): Promise<TachyonContentSurfaceState & { open: false }>;
  };

  interface TachyonCaptureWindow {
    windowId: string;
    title: string;
    application: string;
    frame: { x: number; y: number; width: number; height: number };
  }
  interface TachyonCaptureResult {
    windowId: string;
    destination: 'clipboard' | 'file' | 'both';
    format: 'png';
    bytes: number;
    clipboard: boolean;
    path: string;
  }
  const screenCapture: {
    state(): Promise<{ supported: boolean; permission: 'granted' | 'prompt' | 'denied' | 'unsupported'; format: 'png'; destinations: Array<'clipboard' | 'file' | 'both'> }>;
    listWindows(options?: { visibleOnly?: boolean; excludeCurrentApp?: boolean }): Promise<{ windows: TachyonCaptureWindow[]; permission: 'granted' | 'prompt' | 'unsupported' }>;
    captureWindow(options: { windowId: string; destination: 'clipboard' | 'file' | 'both'; format?: 'png' }): Promise<TachyonCaptureResult>;
  };
  const capabilities: {
    supports(capability: string): boolean;
    state(capability: string): Promise<'granted' | 'denied' | 'prompt' | 'unsupported'>;
  };

  interface Window {
    __tachyonNativeHostCall?: (capability: string, payload: string) => string;
    __tachyonNativeUI?: {
      render(): Promise<unknown>;
      dispatch(event: unknown): Promise<unknown>;
      emit(event: unknown): Promise<unknown>;
    };
  }
}

export {};
