#!/usr/bin/env bun
for await(const chunk of Bun.stdin.stream()) {

    console.log("Executing Bun....");

    const data = new TextDecoder().decode(chunk)

    const ctx = JSON.parse(data)

    ctx.message = "Hello from Bun!"

    const response = JSON.stringify(ctx)

    await Bun.write(`/tmp/${process.pid}`, response)
}

export {}
