#!/usr/bin/env bun

const request = await Bun.stdin.json()
const result = {
    message: 'Hello from Yon on Bun!',
    runtime: {
        name: 'bun',
        version: Bun.version,
    },
    context: request.context,
    frontend: 'Tac',
    backend: 'Yon',
}

Bun.stdout.write(JSON.stringify(result))
