#!/usr/bin/env python3
import json
import sys
import os

print("Executing Python....")

ctx = json.loads(sys.stdin.read())

ctx["message"] = "Hello from Python!"

file = open(f"/tmp/{os.getpid()}", "w")

file.write(json.dumps(ctx))

file.close()