#!/usr/bin/env php
<?php

while(FALSE !== ($line = fgets(STDIN))) {

    $ctx = json_decode($line, true); 

    echo "Executing PHP...\n"; 

    $ctx["message"] = "Hello from PHP!";

    $pid = getmypid();

    $file = fopen("/tmp/$pid", "w");

    fwrite($file, json_encode($ctx));

    fclose($file);
}

?>