#!/usr/bin/perl
use strict;
use warnings;
use JSON;

print "Executing Perl...\n";

# Read input from STDIN
my $input = <STDIN>;
chomp $input;

# Parse JSON
my $json = JSON->new;
my $request = $json->decode($input);

# Print context as JSON
print $json->encode($request->{context}) . "\n";

# Print message as JSON
my $response = { message => 'Hello from Perl!' };
print $json->encode($response);