#!/usr/bin/env bun

const request = await Bun.stdin.json()

Bun.stdout.write(JSON.stringify({
    message: 'Hello from Yon on Bun!',
    method: 'DELETE',
    version: request.paths?.version ?? 'v1',
    context: request.context,
}))
