#!/usr/bin/env bun

import { watch } from "fs/promises";

console.log("Executing Bun...");

const { context } = await Bun.stdin.json()

console.log(`Context:`, context)

for await(const _ of watch(`${process.cwd()}/components`, { recursive: true })) {
    console.log("Changed detected")
    Bun.stdout.write(JSON.stringify({ message: "Hello from Bun"}))
}

export {}