#!/usr/bin/env node
const readline = require('readline')

console.log("Executing Node.js...")

const rl = readline.createInterface({ input: process.stdin })

rl.on('line', (line) => {
    const request = JSON.parse(line)
    console.log(JSON.stringify(request.context))
    const result = { message: "Hello from Node.js!" }
    process.stdout.write(JSON.stringify(result))
    rl.close()
})