#!/usr/bin/env python3
import json
import sys

print("Executing Python...")

stdin = json.loads(sys.stdin.read())

print(stdin["context"])

sys.stdout.write(json.dumps({ "message": "Hello from Python!" }))