#!/usr/bin/env node

const chunks = []
process.stdin.on('data', c => chunks.push(c))
process.stdin.on('end', () => {
    const { body } = JSON.parse(Buffer.concat(chunks).toString())

    if (!body?.name) {
        process.stdout.write(JSON.stringify({ detail: 'name is required' }))
        return
    }

    process.stdout.write(JSON.stringify({ id: crypto.randomUUID(), name: body.name }))
})
